### ISSUE TITLE
`project_name` uses the project folder instead of the output folder

### ISSUE THREAD

**Issue by andriygm** [A2-ai/spackle#12]
For example, when you run
```
just run fill --dir tests/data/project_name
```
the output includes `project_name` instead of `render` etc.

**Comment by dpastoor** [comment]
be very aware that I chaged this behavior as well https://github.com/A2-ai/spackle/pull/11/files in here to use `_project_name` as generally the project name itself was not really what we care about much, we generally want to have a placeholder name that we fill in, eg the project itself will be like "starter"/"template"/"etc" so more likely that will be a slot to collect what they want to call the new project
